main/review/models.py
from .. import db
from ..institute.models import *


class Review(db.Model):
    __tablename__ = 'reviews'
    i_r_d = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(100), index=True, nullable=False)
    last_name = db.Column(db.String(100), index=True, nullable=False)
    content = db.Column(db.Text(), index=True, nullable=False)
    date_created = db.Column(db.DateTime, default=db.func.current_timestamp())
    date_modified = db.Column(db.DateTime, default=db.func.current_timestamp(), onupdate=db.func.current_timestamp()) 
    institute_id = db.Column(db.Integer, db.ForeignKey('institute.i_i_d'))

    def __init__(self, first_name, last_name, content, institute_id):
        self.first_name = first_name
        self.last_name = last_name
        self.content = content
        self.institute_id = institute_id

main/review/__init__.py
from flask import Blueprint

review_bp = Blueprint('review', __name__, url_prefix='/reviews', template_folder='templates', static_folder='static',  static_url_path='/review/static')

from .views import *
from .form import *

main/review/views.py
from flask import request, render_template, url_for, redirect, session
from .. import db
from .models import Review
from ..institute.models import *
from ..institute.views import *
from . import review_bp
from .form import ReviewForm



@review_bp.route('/Review')
def refer():
        review_form = ReviewForm()
        return render_template("UserReviewForm.html", form=review_form)



@review_bp.route('/ReviewDone', methods=['GET', 'POST'])



def U_D_C_1():
        review_form = ReviewForm()
        iwrem=session['BBB_ins_wss']
        theUser = Institute.query.filter_by(institute_website=iwrem).first()
  
        
        if request.method == 'POST':
                        first_name = request.form.get('first_name')
                        last_name = request.form.get('last_name')
                        content = request.form.get('content')
                        
                        if review_form.validate_on_submit(): 
                                bbb = Review(first_name=first_name, last_name=last_name, content=content, institute_id=theUser.i_i_d)
                                db.session.add(bbb)
                                db.session.commit()
                                       
                                session.clear()
                                return redirect(url_for('wall.S_I_L'))

        
        return render_template("UserReviewForm.html", form=review_form)

main/review/templates/InstituteForm.html
{% extends 'home.html' %}

{%block content%}

<div class="w3-padding-tiny" id="main">
  
  <center>
    <br><br><br>
      <div class="w3-card-4 w3-padding w3-round-xlarge w3-hide-small w3-white w3-hide-medium" style="width:40%">
      <img src="{{url_for('review.static', filename='bbb.jpg')}}" class="w3-circle w3-white w3-border-white w3-card-4" style="padding:4px" width="107" height="99"/>
  <form method='POST' action="{{url_for('institute.U_D_C_0')}}"  class="w3-container w3-padding-small w3-card-4 w3-light-grey w3-text-blue w3-margin">
  <h2 class="w3-center w3-text-red "><strong>Fill Up All Boxes</strong></h2>
  
  {{ form.hidden_tag() }}

  <div class="w3-row w3-section">
    <div class="w3-col w3-padding-small" style="width:50px"><i class="w3-xlarge fas fa-school"></i></div>
    <div class="w3-rest">
          {{ form.institute_name(placeholder="Enter Institute's Full Name...", class="w3-input w3-border") }}
          {% if form.institute_name.errors %}
            <div style="color:rgb(255, 17, 0)">{% for error in form.institute_name.errors %}{{ error }}{% endfor %}</div>
          {% endif %}
    </div>
  </div>
  
  <div class="w3-row w3-section">
    <div class="w3-col w3-padding-small" style="width:50px"><i class=" w3-xxlarge material-icons">place</i></div>
    <div class="w3-rest">
        {{ form.institute_address(placeholder='Enter Institute Address [City/Town name only]', class="w3-input w3-border") }}
        {% if form.institute_address.errors %}
          <div style="color:rgb(255, 17, 0)">{% for error in form.institute_address.errors %}{{ error }}{% endfor %}</div>
        {% endif %}
    </div>
  </div>

  
  <!---- <div class="w3-center w3-text-black " style="font-size: 13px"><i>Please type website name carefully! It must be accurate. If you don't know Institute Website, click </i><strong class="w3-text-red">"Find Here" </strong> <i>button</i></div><br>  -->
  
 
     
    <center><button  id="myBtn1"  onclick="myFunction()"  class="w3-button w3-round w3-blue">Find Institute</button></center><br>

  
  <!-- <button   onclick="document.getElementById('id01').style.display='block'" class="w3-button w3-block w3-section w3-blue w3-round w3-ripple w3-padding">Send</button> -->
   


  <script>
    function myFunction() {
      document.getElementById("myBtn1").disabled = true;
    }
  </script>


  </form><br>

</div>
  
  </center>
    
  
  
  
  
  
  
  
  <center><br>
      <div class="w3-card-4 w3-padding w3-round-xlarge w3-white w3-hide-large w3-hide-small" style="width:60%">
     <img src="{{url_for('review.static', filename='bbb.jpg')}}" class="w3-circle w3-white w3-border-white w3-card-4" style="padding:4px" width="107" height="99"/>
  <form method='POST' action="{{url_for('institute.U_D_C_0')}}"   class="w3-container-small  w3-card-4 w3-light-grey w3-text-blue w3-margin">
  <h2 class="w3-center w3-text-red"><strong>Fill Up All Boxes</strong></h2>
  
  {{ form.hidden_tag() }}
  
  <div class="w3-row w3-section w3-small">
    <div class="w3-col w3-padding-small" style="width:40px"><i class="w3-xlarge fas fa-school"></i></div>
      <div class="w3-rest w3-padding-small">
        <div class="w3-rest">
          {{ form.institute_name(placeholder="Enter Institute's Full Name...", class="w3-input w3-border") }}
          {% if form.institute_name.errors %}
            <div style="color:rgb(255, 17, 0)">{% for error in form.institute_name.errors %}{{ error }}{% endfor %}</div>
          {% endif %}
        </div>
      </div>
  </div>
  
  <div class="w3-row w3-section w3-small">
    <div class="w3-col w3-padding-small" style="width:40px"><i class=" w3-xxlarge material-icons">place</i></div>
      <div class="w3-rest w3-padding-small">
          <div class="w3-rest">
            {{ form.institute_address(placeholder='Enter Institute Address  [City/Town name only]', class="w3-input w3-border") }}
            {% if form.institute_address.errors %}
            <div style="color:rgb(255, 17, 0)">{% for error in form.institute_address.errors %}{{ error }}{% endfor %}</div>
            {% endif %}
          </div>
      </div>
  </div>
  

  
  <!-- <div class="w3-center w3-text-black w3-padding-small" style="font-size: 11px"><i>Please type website name carefully! It must be accurate. If you don't know Institute Website, click </i><strong class="w3-text-red">"Find Here" </strong> <i>button</i></div><br> -->
  
  <center><button  id="myBtn2"  onclick="myFunctionn()" class="w3-button w3-round w3-blue">Find Institute</button></center><br>
  
     
  
  <script>
    function myFunctionn() {
      document.getElementById("myBtn2").disabled = true;
    }
  </script>


  
  </form><br>
    </div><br>
  
  </center>
  
  
  
  
  
  <center><br>
  <div class="w3-padding-tiny w3-mobile w3-hide-large w3-hide-medium">
    
  <form method='POST' action="{{url_for('institute.U_D_C_0')}}"  class=" w3-container-small w3-card-4 w3-round-xlarge w3-light-grey w3-text-blue w3-margin">
  <br><img src="{{url_for('review.static', filename='bbb.jpg')}}" class="w3-circle w3-white w3-border-white w3-card-4" style="padding:4px" width="107" height="99">
   
  {{ form.hidden_tag() }}
  
  <div class="w3-row w3-section w3-tiny">
    <div class="w3-col w3-padding-small" style="width:40px"><i class="w3-xlarge fas fa-school"></i></div>
      <div class="w3-rest w3-padding-small">
          <div class="w3-rest">
            {{ form.institute_name(placeholder="Enter Institute's Full Name...", class="w3-input w3-border") }}
            {% if form.institute_name.errors %}
              <div style="color:rgb(255, 17, 0)">{% for error in form.institute_name.errors %}{{ error }}{% endfor %}</div>
            {% endif %}
          </div>
      </div>
  </div>
  
  <div class="w3-row w3-section w3-tiny">
    <div class="w3-col w3-padding-small" style="width:40px"><i class=" w3-xxlarge material-icons">place</i></div>
      <div class="w3-rest w3-padding-small">
          <div class="w3-rest">
            {{ form.institute_address(placeholder='Enter Institute Address [City/Town name only]', class="w3-input w3-border") }}
            {% if form.institute_address.errors %}
              <div style="color:rgb(255, 17, 0)">{% for error in form.institute_address.errors %}{{ error }}{% endfor %}</div>
            {% endif %}
          </div>
      </div>
  </div>
  

  <!-- <div class="w3-center w3-text-black w3-padding-small" style="font-size: 10px"><i>Please type website name carefully! It must be accurate. If you don't know Institute Website, click </i><strong class="w3-text-red">"Find Here" </strong> <i>button</i></div><br>  -->
  
  <center> <button   id="myBtn3"  onclick="myFunctionnn()"   class="w3-button w3-round w3-tiny w3-blue" style="width: 50%" >Find Institute</button> </center><br><br>

     

  <script>
    function myFunctionnn() {
      document.getElementById("myBtn3").disabled = true;
    }
  </script>


  

  </form>

  </div>
  
  </center>
  
  
  
  
  </div>
  

{%endblock%}
  

main/review/templates/InstituteParticular.html
{% extends 'home.html' %}

{%block content%}

<div class="w3-padding-large" id="main">

<center>
  {% for il in i_l %}
    <div class=" w3-padding-small w3-round-large w3-hide-small w3-sand w3-white w3-hide-medium" style="width:40%">
 
<div class=" w3-container w3-sand w3-text-black w3-margin"><br>
 <div class="w3-card-4">
    
    {% if il.institute_logo == "Not Found!" %}
    
        <img src="{{url_for('review.static', filename='noimage.jpg')}}" style="width:100%">

    {% else %}

        <img src="{{il.institute_logo}}"   style="width:100%" >
    
    {% endif %}

 </div>
<div class="w3-row w3-section">
    <div class="w3-content">
       <h1 class="w3-xlarge w3-padding w3-card-4 w3-red w3-text-shadow"><strong>{{il.institute_name}}</strong></h1>
       
      <div class="w3-content w3-justify">
        <h6 style="font-size: 14px">Address: <i class="w3-text-blue">{{il.institute_address}}</i></h6>
       <h6 style="font-size: 14px">Founded In: <i class="w3-text-blue">{{il.institute_founded_in}}</i></h6>
       <h6 style="font-size: 14px">Website: <i class="w3-text-blue"><a href="{{il.institute_website}}">{{il.institute_website}}</a></i></h6>
       <h6 style="font-size: 14px">Map: <i class="w3-text-blue"><a href="{{il.institute_map}}">See Map</a></i></h6>
     </div>
    </div>
</div>

<div class="w3-row w3-section">
    <div class="w3-content w3-justify">
       <h5 style="font-size:16px">{{il.institute_desc}}<i class="w3-text-blue" style="font-size: 14px"><a href="{{url_for('wall.I_P_R', ins_id = il.i_i_d)}}"> See Review</a></i></h5>
    </div>
</div>

</div>
  </div>
  <br>
  {% endfor %}
</center>




<center>
  {% for il in i_l %}
    <div class=" w3-padding-small w3-round-large w3-hide-large w3-sand w3-white w3-hide-small" style="width:80%">
 
<div class=" w3-container w3-sand w3-text-black w3-margin"><br>
 <div class="w3-card-4">
  {% if il.institute_logo == "Not Found!" %}
    
  <img src="{{url_for('review.static', filename='noimage.jpg')}}" style="width:100%">

  {% else %}

  <img src="{{il.institute_logo}}"   style="width:100%" >

  {% endif %}
 </div>

<div class="w3-row w3-section">
    <div class="w3-content">
       <h1 class="w3-xlarge w3-card-4 w3-padding w3-red w3-text-shadow"><strong>{{il.institute_name}}</strong></h1>
       
      <div class="w3-content w3-justify">
          <h6 style="font-size: 13px">Address: <i class="w3-text-blue">{{il.institute_address}}</i></h6>
          <h6 style="font-size: 13px">Founded In: <i class="w3-text-blue">{{il.institute_founded_in}}</i></h6>
          <h6 style="font-size: 13px">Website: <i class="w3-text-blue"><a href="{{il.institute_website}}">{{il.institute_website}}</a></i></h6>
          <h6 style="font-size: 13px">Map: <i class="w3-text-blue"><a href="{{il.institute_map}}">See Map</a></i></h6>
     </div>
    </div>
</div>

<div class="w3-row w3-section">
    <div class="w3-content w3-justify">
       <h5 style="font-size:15px">{{il.institute_desc}}<i class="w3-text-blue" style="font-size: 13px"><a href="{{url_for('wall.I_P_R', ins_id = il.i_i_d)}}"> See Review</a></i></h5>
    </div>
</div>

</div>
</div>
<br>
{% endfor %}
</center>



<center>
  {% for il in i_l %}
    <div class=" w3-padding-small w3-round-large w3-mobile w3-hide-large w3-sand w3-white w3-hide-medium">
 
<div class=" w3-container w3-sand w3-text-black w3-margin"><br>
 <div class="w3-card-4">
  {% if il.institute_logo == "Not Found!" %}
    
  <img src="{{url_for('review.static', filename='noimage.jpg')}}" style="width:100%">

{% else %}

  <img src="{{il.institute_logo}}"   style="width:100%" >

 {% endif %}
 
 </div>
<div class="w3-row w3-section">
    <div class="w3-content">
       <h1 class="w3-red w3-card-4 w3-large w3-padding-small w3-text-shadow"><strong>{{il.institute_name}}</strong></h1>
       
      <div class="w3-content w3-justify">
          <h6 style="font-size: 10px">Address: <i class="w3-text-blue">{{il.institute_address}}</i></h6>
          <h6 style="font-size: 10px">Founded In: <i class="w3-text-blue">{{il.institute_founded_in}}</i></h6>
          <h6 style="font-size: 10px">Website: <i class="w3-text-blue"><a href="{{il.institute_website}}">{{il.institute_website}}</a></i></h6>
          <h6 style="font-size: 10px">Map: <i class="w3-text-blue"><a href="{{il.institute_map}}">See Map</a></i></h6>
     </div>
    </div>
</div>

<div class="w3-row w3-section">
    <div class="w3-content w3-justify">
       <h5 style="font-size: 13px">{{il.institute_desc}}<i class="w3-text-blue" style="font-size: 10px"><a href="{{url_for('wall.I_P_R', ins_id = il.i_i_d)}}"> See Review</a></i></h5>
    </div>
</div>
</div>
  </div>
  <br>
  {% endfor %}
</center>

  <!-- END PAGE CONTENT -->
</div>

{%endblock%}

main/review/templates/MBFC.html
<!DOCTYPE html>
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-colors-metro.css">
<body class="w3-dark-gray">


  <div class="w3-padding-large" id="main">
    <div class="w3-container">
   
    <div class="w3-content w3-justify w3-text-white w3-padding-32">
      <center>
        <img src="{{url_for('review.static', filename='bbb.jpg')}}" class="w3-circle w3-black w3-border-white w3-card-4" style="padding:4px" width="142" height="130">

          <h3>IDENTIFY INSTITUTE</h3>
          <hr style="width:50%" class="w3-opacity">
          <h5  class="w3-content w3-justify w3-text-white w3-padding-32">Indentify and confirm the institute about which you want to give review. If the institute is not that what you want then please cancel and retype institute's name and address correctly.</h5>
          <button onclick="document.getElementById('id01').style.display='block'" class="w3-button w3-blue w3-large">Continue</button>
      </center>

    </div>









  <div id="id01" class="w3-modal">
    <div class="w3-modal-content w3-light-gray w3-card-4 w3-animate-zoom" style="max-width:600px">

      <br>
        <div class="w3-container w3-center" >
            <h1 class="w3-blue w3-card-2 w3-round-large w3-large w3-padding-small w3-text-shadow"><strong>Is This What On which You Want To Write Review?</strong></h1>
           
        </div>

      <div class="w3-container w3-center" >
        <div class="w3-section">
          <div class="w3-white w3-round-xlarge w3-card-4 w3-padding">
              <h1 class=" w3-large w3-text-shadow"><strong>{{title}}</strong></h1>
              
              {% if srcc == "Not Found!" %}
                   <img src="{{url_for('review.static', filename='noimage.jpg')}}"  style="width:50%" class=" w3-margin-top "  style="width:50%" class=" w3-margin-top ">
        
              {% else %}
                   <img src="{{srcc}}"   style="width:50%" class=" w3-margin-top "  style="width:50%" class=" w3-margin-top ">
              {% endif %}
       
              <div class="w3-content w3-justify ">
                
                <h6 style="font-size: 13px"><b>Established:</b> <i class="w3-text-blue" style="font-size: 14px">{{founded_in}}</i></h6>
                <h6 style="font-size: 13px"><b>Address:</b> <i class="w3-text-blue" style="font-size: 14px">{{address}}</i></h6>
                <h6 style="font-size: 13px"><b>Map:</b> <i class="w3-text-blue" style="font-size: 14px"><a href="{{loctn}}">Click Here To See On Map</a></i></h6>
                <h6 style="font-size: 13px"><b>Website:</b> <i class="w3-text-blue" style="font-size: 14px"><a href="{{linkk}}">{{linkk}}</a></i></h6>
              </div>
        </div>
      </div>
     </div>


      <div class="w3-container w3-border-top w3-padding-16 w3-light-grey">
        <!--<button onclick="document.getElementById('id01').style.display='none'" type="button" class="w3-btn w3-green">Cancel</button> -->
        <span class="w3-left"><a href="{{url_for('institute.U_D_C_0')}}"  class="w3-btn w3-green">Cancel</a></span>
        <span class="w3-right"><a href="{{url_for('institute.I_D_C')}}"  class="w3-btn w3-red">Confirm</a></span>
      </div>

    </div>
    <br><br><br><br><br><br>
  </div>
</div>
</div>

            
</body>
</html>

main/review/templates/UserReviewForm.html
{% extends 'home.html' %}

{%block content%}


<div class="w3-padding-large" id="main">
  
<center>
  <br><br>
    <div class="w3-card-4 w3-padding w3-round-xlarge w3-hide-small w3-white w3-hide-medium" style="width:40%">
    <img  src="{{url_for('review.static', filename='bbb.jpg')}}"  class="w3-circle w3-white w3-border-white w3-card-4" style="padding:4px" width="107" height="99">
<form method='POST' action="{{url_for('review.U_D_C_1')}}" class="w3-container w3-card-4 w3-light-grey w3-text-blue w3-margin">
<h2 class="w3-center w3-text-red "><strong>Fill Up All Boxes</strong></h2>

{{ form.hidden_tag() }}
 
<div class="w3-row w3-section">
  <div class="w3-col w3-padding-small" style="width:50px"><i class="w3-xlarge far fa-user"></i></div>
    <div class="w3-rest">
      {{ form.first_name(placeholder='First Name...', class="w3-input w3-border") }}
      {% if form.first_name.errors %}
        <div style="color:rgb(255, 17, 0)">{% for error in form.first_name.errors %}{{ error }}{% endfor %}</div>
      {% endif %}
    </div>
</div>

<div class="w3-row w3-section">
  <div class="w3-col w3-padding-small" style="width:50px"><i class=" w3-xlarge far fa-user"></i></div>
    <div class="w3-rest">
      {{ form.last_name(placeholder='Last Name...', class="w3-input w3-border") }}
          {% if form.last_name.errors %}
            <div style="color:rgb(255, 17, 0)">{% for error in form.last_name.errors %}{{ error }}{% endfor %}</div>
          {% endif %}
    </div>
</div>

<div class="w3-row w3-section">
  <div class="w3-col w3-padding-small" style="width:50px"><i class="w3-xlarge far fa-edit"></i></div>
    <div class="w3-rest">
        {{ form.content(placeholder="Review the institute covering these all topics 'Entrance Preview'  'Fee Structure And Facilities'  'Placement Wing'  'Hostel Facilities'  'Faculty And Alumni'  'Campus Life'  'Exam Structure'  'Course Curriculum Overview'  'Internship Opportunities' & 'Loan/Scholarship Provisions' ", class="w3-input w3-border") }}
        {% if form.content.errors %}
          <div style="color:rgb(255, 17, 0)">{% for error in form.content.errors %}{{ error }}{% endfor %}</div>
        {% endif %}
    </div>
</div>

<center><button  id="myBtn1"  onclick="myFunction()"  class="w3-button w3-round w3-blue">Find Institute</button></center><br>

<script>
  function myFunction() {
    document.getElementById("myBtn1").disabled = true;
  }
</script>

</form>
  </div>
  <br>

</center>








<center>
    <div class="w3-card-4 w3-padding w3-round-xlarge w3-white w3-hide-large w3-hide-small" style="width:60%">
   <img  src="{{url_for('review.static', filename='bbb.jpg')}}"  class="w3-circle w3-white w3-border-white w3-card-4" style="padding:4px" width="107" height="99">
<form method='POST' action="{{url_for('review.U_D_C_1')}}" class="w3-container-small  w3-card-4 w3-light-grey w3-text-blue w3-margin">
<h2 class="w3-center w3-text-red"><strong>Fill Up All Boxes</strong></h2>

{{ form.hidden_tag() }}
 
<div class="w3-row w3-section w3-small">
  <div class="w3-col w3-padding-small" style="width:40px"><i class="w3-xlarge far fa-user"></i></div>
    <div class="w3-rest w3-padding-small">
      {{ form.first_name(placeholder='First Name...', class="w3-input w3-border") }}
      {% if form.first_name.errors %}
        <div style="color:rgb(255, 17, 0)">{% for error in form.first_name.errors %}{{ error }}{% endfor %}</div>
      {% endif %}
    </div>
</div>

<div class="w3-row w3-section w3-small">
  <div class="w3-col w3-padding-small" style="width:40px"><i class=" w3-xlarge far fa-user"></i></div>
    <div class="w3-rest w3-padding-small">
      {{ form.last_name(placeholder='Last Name...', class="w3-input w3-border") }}
      {% if form.last_name.errors %}
        <div style="color:rgb(255, 17, 0)">{% for error in form.last_name.errors %}{{ error }}{% endfor %}</div>
      {% endif %}
    </div>
</div>

<div class="w3-row w3-section w3-small">
  <div class="w3-col w3-padding-small" style="width:40px"><i class="w3-xlarge far fa-edit"></i></div>
    <div class="w3-rest w3-padding-small">
        {{ form.content(placeholder="Review the institute covering these all topics 'Entrance Preview'  'Fee Structure And Facilities'  'Placement Wing'  'Hostel Facilities'  'Faculty And Alumni'  'Campus Life'  'Exam Structure'  'Course Curriculum Overview'  'Internship Opportunities' & 'Loan/Scholarship Provisions' ", class="w3-input w3-border") }}
        {% if form.content.errors %}
          <div style="color:rgb(255, 17, 0)">{% for error in form.content.errors %}{{ error }}{% endfor %}</div>
        {% endif %}
    </div>
</div>

<center><button  id="myBtn2"  onclick="myFunctionn()" class="w3-button w3-round w3-blue">Find Institute</button></center><br>
  
     
  
  <script>
    function myFunctionn() {
      document.getElementById("myBtn2").disabled = true;
    }
  </script>


</form>
  </div>
  <br><br>

</center>






<center>
    <div class="w3-padding-tiny w3-mobile w3-hide-large w3-hide-medium " >
  
<form method='POST' action="{{url_for('review.U_D_C_1')}}" class="w3-container-small w3-card-4 w3-round-xlarge w3-light-grey w3-text-blue w3-margin">
<br><img  src="{{url_for('review.static', filename='bbb.jpg')}}"  class="w3-circle w3-white w3-border-white w3-card-4" style="padding:4px" width="107" height="99">

{{ form.hidden_tag() }}
 
<div class="w3-row w3-section w3-tiny">
  <div class="w3-col w3-padding-small" style="width:40px"><i class="w3-xlarge far fa-user"></i></div>
    <div class="w3-rest w3-padding-small">
      {{ form.first_name(placeholder='First Name...', class="w3-input w3-border") }}
      {% if form.first_name.errors %}
        <div style="color:rgb(255, 17, 0)">{% for error in form.first_name.errors %}{{ error }}{% endfor %}</div>
      {% endif %}
    </div>
</div>

<div class="w3-row w3-section w3-tiny">
  <div class="w3-col w3-padding-small" style="width:40px"><i class=" w3-xlarge far fa-user"></i></div>
    <div class="w3-rest w3-padding-small">
      {{ form.last_name(placeholder='Last Name...', class="w3-input w3-border") }}
      {% if form.last_name.errors %}
        <div style="color:rgb(255, 17, 0)">{% for error in form.last_name.errors %}{{ error }}{% endfor %}</div>
      {% endif %}
    </div>
</div>

<div class="w3-row w3-section w3-tiny">
  <div class="w3-col w3-padding-small" style="width:40px"><i class="w3-xlarge far fa-edit"></i></div>
    <div class="w3-rest w3-padding-small">
        {{ form.content(placeholder="Review the institute covering these all topics 'Entrance Preview'  'Fee Structure And Facilities'  'Placement Wing'  'Hostel Facilities'  'Faculty And Alumni'  'Campus Life'  'Exam Structure'  'Course Curriculum Overview'  'Internship Opportunities' & 'Loan/Scholarship Provisions' ", class="w3-input w3-border") }}
        {% if form.content.errors %}
          <div style="color:rgb(255, 17, 0)">{% for error in form.content.errors %}{{ error }}{% endfor %}</div>
        {% endif %}
    </div>
</div>

<center> <button   id="myBtn3"  onclick="myFunctionnn()"   class="w3-button w3-round w3-tiny w3-blue" style="width: 50%" >Find Institute</button> </center><br>

     

  <script>
    function myFunctionnn() {
      document.getElementById("myBtn3").disabled = true;
    }
  </script>

  
</form>
  </div>

</center>
<br>


  <!-- END PAGE CONTENT -->
</div>

</body>
</html>

{%endblock%}

main/review/templates/index1.html
<html>
  <head>
    <title>Review</title>
  </head>
  <body>
     <center>
            <div style="color:rgb(255, 17, 0)"><h1>Hello Type something to begin!</h1></div>
            <form method='POST' action="{{url_for('review.U_D_C_1')}}">

              {{ form.first_name(placeholder='Enter First Name...') }} {{ form.first_name.label }}<br><br>
              {% if form.first_name.errors %}
                <div style="color:rgb(255, 17, 0)">{% for error in form.first_name.errors %}{{ error }}{% endfor %}</div>
              {% endif %}
              <br>

              
              {{ form.last_name(placeholder='Enter Last Name...') }} {{ form.last_name.label }}<br><br>
              {% if form.last_name.errors %}
                <div style="color:rgb(255, 17, 0)">{% for error in form.last_name.errors %}{{ error }}{% endfor %}</div>
              {% endif %}
              <br>


              {{ form.content(placeholder='Enter Review...') }} {{ form.content.label }}<br><br>
              {% if form.content.errors %}
                <div style="color:rgb(255, 17, 0)">{% for error in form.content.errors %}{{ error }}{% endfor %}</div>
              {% endif %}
              <br><br>


            <input type="submit" value="Comment"/>
            </form>
            <br>
            <img src="{{url_for('review.static', filename='bbb.jpg')}}"/>
    </center>
  </body>
</html>